### ISSUE TITLE
API // Project structure

### ISSUE THREAD

**Issue by AleksSenkou** [datarockets/rails_apps_composer#23]
### Main Idea
Let's have a clear project :1st_place_medal: 

### Changes

* [x] Remove `app/assets` folder

* [x] No need in `protect_from_forgery` in `application_controller`. API!

* [x] Remove `app/helpers` folder

* [x] `public` folder shouldn't have such files as `404.html`

* [x] Add api only config to `Application` class in `application.rb`:
```ruby
module AppName
  class Application < Rails::Application
    config.api_only = true
  end
end
```

look [here](https://github.com/datarockets/bevital/blob/master/config/application.rb)

* [x] Remove `config/initializers/assets.rb` initializer

* [x] we've added `jbuilder` but forget to add initializer for it. `config/initializers/jbuilder.rb` with
```ruby
Jbuilder.key_format(camelize: :lower)
```
should be added by default ^, see [documentation](https://github.com/rails/jbuilder#jbuilder)

* [x] Let's change default `database.yml` to:
```yaml
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: app_name_development

test:
  <<: *default
  database: app_name_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
```

* [x] Default `sercerts.yml`:
```yaml
environment: &environment
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

development: &development
  <<: *environment

test:
  <<: *development
  secret_key_base: some_secret_key

production:
  <<: *environment

staging:
  <<: *environment
```

###### P.S. Ping me if you are not agree, or have better idea.
